In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("teleCust1000t.xlsx")

In [3]:
df.info

<bound method DataFrame.info of      region  tenure  age  marital  address  income  ed  employ  retire  \
0         2      13   44        1        9      64   4       5       0   
1         3      11   33        1        7     136   5       5       0   
2         3      68   52        1       24     116   1      29       0   
3         2      33   33        0       12      33   2       0       0   
4         2      23   30        1        9      30   1       2       0   
..      ...     ...  ...      ...      ...     ...  ..     ...     ...   
995       3      10   39        0        0      27   3       0       0   
996       1       7   34        0        2      22   5       5       0   
997       3      67   59        0       40     944   5      33       0   
998       3      70   49        0       18      87   2      22       0   
999       3      50   36        1        7      39   3       3       0   

     gender  reside  custcat  
0         0       2        1  
1         0      

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   region   1000 non-null   int64
 1   tenure   1000 non-null   int64
 2   age      1000 non-null   int64
 3   marital  1000 non-null   int64
 4   address  1000 non-null   int64
 5   income   1000 non-null   int64
 6   ed       1000 non-null   int64
 7   employ   1000 non-null   int64
 8   retire   1000 non-null   int64
 9   gender   1000 non-null   int64
 10  reside   1000 non-null   int64
 11  custcat  1000 non-null   int64
dtypes: int64(12)
memory usage: 93.9 KB


In [5]:
df.shape

(1000, 12)

In [6]:
df.isnull().sum()

region     0
tenure     0
age        0
marital    0
address    0
income     0
ed         0
employ     0
retire     0
gender     0
reside     0
custcat    0
dtype: int64

In [7]:
df.count()

region     1000
tenure     1000
age        1000
marital    1000
address    1000
income     1000
ed         1000
employ     1000
retire     1000
gender     1000
reside     1000
custcat    1000
dtype: int64

In [8]:
df.custcat.value_counts()

custcat
3    281
1    266
4    236
2    217
Name: count, dtype: int64

In [9]:
df.columns

Index(['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside', 'custcat'],
      dtype='object')

In [10]:
features = df.drop('custcat',axis=1)

In [11]:
df.columns

Index(['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside', 'custcat'],
      dtype='object')

In [12]:
target = df.custcat

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=.25, random_state=101)


In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
model = KNeighborsClassifier(n_neighbors=2)

In [34]:
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [35]:
model.predict(x_test)

array([1, 3, 2, 1, 1, 4, 1, 2, 1, 4, 2, 2, 3, 1, 1, 2, 2, 2, 3, 1, 1, 1,
       1, 2, 1, 3, 1, 2, 1, 2, 1, 3, 1, 1, 1, 3, 1, 3, 2, 1, 1, 1, 2, 3,
       2, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 3, 3, 1, 1, 2, 3, 2, 2, 2,
       3, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 3, 3, 1, 1, 3, 1, 1, 2,
       2, 2, 1, 4, 1, 1, 3, 2, 2, 1, 2, 4, 3, 2, 1, 1, 1, 2, 4, 2, 2, 2,
       1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 3, 3, 1, 1, 3, 2, 4, 1, 1, 1, 2, 1,
       2, 1, 1, 3, 1, 1, 4, 1, 1, 1, 3, 1, 2, 2, 1, 3, 3, 3, 2, 1, 4, 3,
       3, 1, 2, 2, 2, 1, 2, 3, 2, 1, 1, 2, 1, 2, 1, 1, 2, 3, 2, 3, 1, 2,
       2, 1, 3, 3, 2, 4, 3, 1, 1, 2, 2, 3, 1, 2, 2, 1, 4, 1, 1, 4, 3, 3,
       2, 1, 1, 2, 3, 2, 1, 2, 1, 3, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 4,
       3, 1, 3, 1, 1, 1, 1, 4, 3, 3, 3, 1, 3, 2, 2, 2, 1, 1, 3, 3, 1, 1,
       2, 1, 3, 3, 1, 2, 4, 3], dtype=int64)

In [36]:
y_pred=model.predict(x_test)

In [37]:
print(y_pred)

[1 3 2 1 1 4 1 2 1 4 2 2 3 1 1 2 2 2 3 1 1 1 1 2 1 3 1 2 1 2 1 3 1 1 1 3 1
 3 2 1 1 1 2 3 2 1 3 1 1 1 1 3 1 1 1 1 2 3 3 1 1 2 3 2 2 2 3 1 1 2 2 1 1 2
 1 1 1 1 1 2 3 3 1 1 3 1 1 2 2 2 1 4 1 1 3 2 2 1 2 4 3 2 1 1 1 2 4 2 2 2 1
 2 1 2 2 1 1 1 1 2 3 3 1 1 3 2 4 1 1 1 2 1 2 1 1 3 1 1 4 1 1 1 3 1 2 2 1 3
 3 3 2 1 4 3 3 1 2 2 2 1 2 3 2 1 1 2 1 2 1 1 2 3 2 3 1 2 2 1 3 3 2 4 3 1 1
 2 2 3 1 2 2 1 4 1 1 4 3 3 2 1 1 2 3 2 1 2 1 3 2 2 2 2 1 1 1 2 2 1 2 4 3 1
 3 1 1 1 1 4 3 3 3 1 3 2 2 2 1 1 3 3 1 1 2 1 3 3 1 2 4 3]


In [38]:
from sklearn.metrics import classification_report


In [39]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.31      0.56      0.40        61
           2       0.36      0.47      0.41        58
           3       0.33      0.27      0.30        64
           4       0.43      0.09      0.15        67

    accuracy                           0.34       250
   macro avg       0.36      0.34      0.31       250
weighted avg       0.36      0.34      0.31       250



In [40]:
features.to_numpy()

array([[ 2, 13, 44, ...,  0,  0,  2],
       [ 3, 11, 33, ...,  0,  0,  6],
       [ 3, 68, 52, ...,  0,  1,  2],
       ...,
       [ 3, 67, 59, ...,  0,  1,  1],
       [ 3, 70, 49, ...,  0,  1,  1],
       [ 3, 50, 36, ...,  0,  1,  3]], dtype=int64)

In [41]:
features.to_numpy()[11]

array([ 3,  7, 35,  0, 14, 80,  2, 15,  0,  1,  1], dtype=int64)